services:
  dev-backend:
    image: node:20-alpine
    container_name: smart-rental-backend-dev
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3002
      - DATABASE_URL=postgresql://smart_rental:smart_rental_password@postgres:5432/smart_rental
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_here
      - SESSION_SECRET=your_session_secret_here
    depends_on:
      - postgres
      - redis
    networks:
      - smart-rental-network

  dev-frontend:
    image: node:20-alpine
    container_name: smart-rental-frontend-dev
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 3002"
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001/api
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    depends_on:
      - dev-backend
    networks:
      - smart-rental-network

networks:
  smart-rental-network:
    name: smartrentalsystem_smart-rental-network
