version: '3.8'

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: smart-rental-libretranslate
    ports:
      - "5002:5000"
    environment:
      - LOAD_ONLY=en,pl
      - THREADS=4
    entrypoint: ["/app/venv/bin/libretranslate"]
    command: ["--host", "0.0.0.0", "--port", "5000", "--load-only", "en,pl", "--threads", "4"]
    volumes:
      - libretranslate_data:/app/data
    restart: unless-stopped

volumes:
  libretranslate_data:
    driver: local
