version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smart-rental-postgres
    environment:
      POSTGRES_DB: smart_rental_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart-rental-network
    restart: unless-stopped

  # Backend API
  backend:
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: smart-rental-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/smart_rental_dev
      - JWT_SECRET=your_jwt_secret_here_change_in_production
      - SESSION_SECRET=your_session_secret_here_change_in_production
      - FRONTEND_URL=http://localhost:5173
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - backend_data:/app/data
    networks:
      - smart-rental-network
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev"
    restart: unless-stopped

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: smart-rental-frontend
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_DEV_SERVER_HOST=0.0.0.0
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - smart-rental-network
    command: npm run dev
    restart: unless-stopped

  # Redis Cache (optional, for future use)
  redis:
    image: redis:7-alpine
    container_name: smart-rental-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-rental-network
    restart: unless-stopped
    profiles:
      - cache

  # Adminer (Database Management) - for SQLite
  adminer:
    image: adminer:latest
    container_name: smart-rental-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: backend
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      - backend
    networks:
      - smart-rental-network
    profiles:
      - tools
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  backend_data:
    driver: local
  redis_data:
    driver: local

networks:
  smart-rental-network:
    driver: bridge 