-- CreateEnum
CREATE TYPE "public"."UserRank" AS ENUM ('NEW_USER', 'BRONZE_TENANT', 'SILVER_TENANT', 'GOLD_TENANT', 'PLATINUM_TENANT', 'BRONZE_LANDLORD', 'SILVER_LANDLORD', 'GOLD_LANDLORD', 'PLATINUM_LANDLORD', 'DIAMOND_LANDLORD');

-- AlterTable
ALTER TABLE "public"."users" ADD COLUMN     "rank" "public"."UserRank" NOT NULL DEFAULT 'NEW_USER',
ADD COLUMN     "rankPoints" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rankUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
